---
title: "Anion Gap No Dup Analysis"
author: "Tyler Cooke"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## 1. Import data

```{r, echo = FALSE}
library(tidyverse)
library(knitr)
library(ggthemes)

setwd(paste0(getwd(), "/.."))
csv2023 <- read.csv(paste0(
  getwd(), "/00. Data/02. Combined Data/AGAP_0611-081923.csv"
))
csv2022 <- read.csv(paste0(
  getwd(), "/00. Data/02. Combined Data/AGAP_0612-082022.csv"
))
csvCombined <- bind_rows(csv2022, csv2023)
```

## 2. Clean data, add Location and prePost variables

-   Filter patient location for Emergency, Inpatient, and Outpatient (including "Private Ambulatory")
-   Add prePost variable (2022 = 0, 2023 = 1)
-   Add Time, Date, and DayOfWeek variables (extracted from PERFORM_DT_TM)

```{r, echo = FALSE}
clean.csv <- function(dataframe) {
  names(dataframe) <- str_replace_all(names(dataframe), "X_", "")
  dataframe$RESULT <- str_trim(dataframe$RESULT, side = "left") %>% 
    as.numeric()
  dataframe <- dataframe %>% 
    filter(!is.na(RESULT)) %>% 
    filter(str_ends(SVCRSC, "C702")) %>% 
    filter(ENCTYP == 'Inpatient' |
             ENCTYP == 'Outpatient' |
             ENCTYP == 'Emergency' |
             ENCTYP == 'Private Ambulatory'
    ) %>%
  mutate(
    Location = case_when(
      ENCTYP == 'Inpatient' ~ 'Inpatient',
      ENCTYP == 'Outpatient' ~ 'Outpatient',
      ENCTYP == 'Emergency' ~ 'Emergency',
      ENCTYP == 'Private Ambulatory' ~ 'Outpatient',
    )
  )
  dataframe$Location <- factor(dataframe$Location,
                                levels = c('Outpatient','Emergency','Inpatient'))
  
  return(dataframe)
}

df <- clean.csv(csvCombined)
df <- df %>% 
  mutate(
    prePost = if_else(str_detect(PERFORM_DT_TM,"/22 "), 0, 1)
  )

df.2022 <- filter(df, prePost == 0)
df.2023 <- filter(df, prePost == 1)

days <- c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday")
dates.2022 <- str_sub(df.2022$PERFORM_DT_TM, start = 1, end = 8)
dates.2022 <- dates.2022[!duplicated(dates.2022)]
dateday.2022 <- data.frame(dates.2022, rep(days, length.out = length(dates.2022)))

dates.2023 <- str_sub(df.2023$PERFORM_DT_TM, start = 1, end = 8)
dates.2023 <- dates.2023[!duplicated(dates.2023)]
dateday.2023 <- data.frame(dates.2023, rep(days, length.out = length(dates.2023)))

df.2022 <- df.2022 %>% 
  mutate(
    DayOfWeek = factor(
      dateday.2022[match(str_sub(PERFORM_DT_TM, start = 1, end = 8),
                                   dateday.2022[,1]),2],
      levels = days
      ),
    Time = str_sub(PERFORM_DT_TM, start = 10, end = 11),
    Date = str_sub(PERFORM_DT_TM, start = 1, end = 8)
  )
  

df.2023 <- df.2023 %>% 
  mutate(
    DayOfWeek = factor(
      dateday.2023[match(str_sub(PERFORM_DT_TM, start = 1, end = 8),
                                   dateday.2023[,1]),2],
      levels = days
      ),
    Time = str_sub(PERFORM_DT_TM, start = 10, end = 11),
    Date = str_sub(PERFORM_DT_TM, start = 1, end = 8)
  )

df.2022.rmdup <- df.2022[!duplicated(df.2022$MRN),]
df.2023.rmdup <- df.2023[!duplicated(df.2023$MRN),]

df.2022.rmdup.wkday <- df.2022.rmdup %>% filter((DayOfWeek != "Saturday") & (DayOfWeek != "Sunday")) 
df.2023.rmdup.wkday <- df.2023.rmdup %>% filter((DayOfWeek != "Saturday") & (DayOfWeek != "Sunday"))



```

## 3. Descriptive Statistics

```{r}
descStats <- function(dataframe, title) {
  output <- data.frame(
    c(
      sapply(
        c(
          length(dataframe$RESULT),
          median(dataframe$RESULT),
          round(mean(dataframe$RESULT), 2),
          round(sd(dataframe$RESULT), 2)
        ),
        as.character
      ),
      paste0(
        as.character(range(dataframe$RESULT))[1],
        " to ",
        as.character(range(dataframe$RESULT))[2]
      )
    ),
  row.names = c("n", "Median", "Mean", "Std. dev.", "Range")
  )
  names(output) <- title
  return(output)
}

ds.2022 <- descStats(df.2022.rmdup, "Descriptive Statistics, 2022 data")
ds.2023 <- descStats(df.2023.rmdup, "Descriptive Statistics, 2023 data")

kable(ds.2022)
kable(ds.2023)
```

## 4. Density Plots

```{r}
plot.2022 <- ggplot(df.2022.rmdup.wkday, aes(x = RESULT)) +
  geom_freqpoly(
    color = "red",
    binwidth = 1) +
  labs(title = "Anion Gap Frequency Plot (weekdays)")

overlay.plot <- plot.2022 + 
  geom_freqpoly(
    data = df.2023.rmdup.wkday,
    color = "blue",
    binwidth = 1) +
  annotate("text", x = 30, y = 5000,label = "Red = 2022", color = "red") +
  annotate("text", x = 30, y = 4700, label = "Blue = 2023", color = "blue")
overlay.plot

dayplot.2022 <- ggplot(df.2022.rmdup, aes(x = DayOfWeek)) +
  geom_bar() +
  labs(title = "2022 Test Count by Day of Week")
print(dayplot.2022)

dayplot.2023 <- ggplot(df.2023.rmdup, aes(x = DayOfWeek)) +
  geom_bar() +
  labs(title = "2023 Test Count by Day of Week")
dayplot.2023

```

## 5. Anion Gap Testing by Time

```{r, echo = FALSE}
by_Time.2022 <- df.2022.rmdup.wkday %>% 
  group_by(Time) %>% 
  summarize(
    Var = var(RESULT),
    Mean = mean(RESULT),
    Min = min(RESULT),
    Max = max(RESULT),
    High = sum(RESULT >= 18),
    Total = n(),
    `High/Total` = High/Total
  ) 

by_Time.2023 <- df.2023.rmdup.wkday %>% 
  group_by(Time) %>% 
  summarize(
    Var = var(RESULT),
    Mean = mean(RESULT),
    Min = min(RESULT),
    Max = max(RESULT),
    High = sum(RESULT >= 18),
    Total = n(),
    `High/Total` = High/Total
  )

ggplot(data = df.2022.rmdup.wkday, aes(x = Time)) +
  geom_bar(aes(fill = RESULT >= 18)) +
  scale_fill_manual(values = c("#1b9e77", "#d95f02")) +
  labs(title = "2022 Number of Tests Run by Hour (weekdays)")

ggplot(data = df.2023.rmdup.wkday, aes(x = Time)) +
  geom_bar(aes(fill = RESULT >= 18)) +
  scale_fill_manual(values = c("#1b9e77", "#d95f02")) +
  labs(title = "2023 Number of Tests Run by Hour (weekdays)")

HighTotal.plot <- ggplot() +
  geom_point(data = by_Time.2022, aes(x = Time, y = High/Total), color = "red")+
  geom_point(data = by_Time.2023, aes(x = Time, y = High/Total), color = "blue") +
  annotate("text", x = 12, y = 0.2,label = "Red = 2022", color = "red") +
  annotate("text", x = 12, y = 0.19, label = "Blue = 2023", color = "blue") +
  labs(title = "Rate of High Anion Gap by Time of Day (weekdays)")
HighTotal.plot

by_Time.2022 %>% print(n=24) %>% kable(caption = "2022 Anion Gap Testing by Hour")
by_Time.2023 %>% print(n=24) %>% kable(caption = "2023 Anion Gap Testing by Hour")

```

### Sensitivity Analysis

```{r, echo = FALSE}
sens.range <- 16:22

sens.df <- data.frame(Time = str_pad(00:23, 2, side = "left", pad = "0"))
for (i in 1:length(sens.range)) {
  col_name <- paste0("Level", sens.range[i])
# HighRate_diff <- function(sens.value, sens.df) {
#   i <- sens.value
  by_Time.2022.sens <- df.2022.rmdup.wkday %>% 
    group_by(Time) %>% 
    summarize(
      Total = n(),
      High = sum(RESULT >= sens.range[i]),
      HighRate = High / Total
    )
  by_Time.2023.sens <- df.2023.rmdup.wkday %>% 
    group_by(Time) %>% 
    summarize(
      Total = n(),
      High = sum(RESULT >= sens.range[i]),
      HighRate = High/Total
    )
  sens.df <- sens.df %>% 
    mutate(
      !!col_name := (by_Time.2022.sens[["HighRate"]] - by_Time.2023.sens[["HighRate"]])
    )
  # return(sens.df)
  }

sens.df <- as.data.frame(t(sens.df))

ggplot(data = sens.df, aes(x = Time)) +
  geom_tile(aes(y = 16, fill = Level16)) +
  geom_tile(aes(y = 17, fill = Level17)) +
  geom_tile(aes(y = 18, fill = Level18)) +
  geom_tile(aes(y = 19, fill = Level19)) +
    geom_tile(aes(y = 20, fill = Level20)) +
    geom_tile(aes(y = 21, fill = Level21)) +
    geom_tile(aes(y = 22, fill = Level22)) +
  scale_fill_gradient(low = "white", high = "purple") +
  scale_y_continuous(n.breaks = 7) +
  ylab("High Value Cut-off")+
  labs(title = "(2022 - 2023) Difference in Rate of High Values", fill = "")
```

## 6. Anion Gap Testing by Day

```{r, echo = FALSE}
by_Date.2022 <- df.2022.rmdup %>% 
  group_by(Date) %>% 
  summarize(
    Day = first(DayOfWeek),
    Line1 = sum(SVCRSC == "U C1C702"),
    Line2 = sum(SVCRSC == "U C2C702"),
    Total = n()
  )

by_Date.2023 <- df.2023.rmdup %>% 
  group_by(Date) %>% 
  summarize(
    Day = first(DayOfWeek),
    Line3 = sum(SVCRSC == "UC3C702"),
    Line4 = sum(SVCRSC == "UC4C702"),
    Line5 = sum(SVCRSC == "UC5C702"),
    Total = n()
  )

ggplot(df.2022.rmdup, aes(x = Date)) +
  geom_bar() +
  labs(title = "2022 Anion Gap Testing by Day")

ggplot(df.2023.rmdup, aes(x = Date)) +
  geom_bar() +
  labs(title = "2023 Anion Gap Testing by Day")

# ggplot(df.2022.rmdup, aes(x = Date)) +
#   geom_line(aes(y = sum(SVCRSC == "U C1C702"))) +
#   geom_line(aes(y = sum(SVCRSC == "U C2C702"))) +
#   labs(title = "2022 Anion Gap Testing by Day")

by_Date.2022 %>% print(n = 50) %>% kable()
by_Date.2023 %>% print(n = 50) %>% kable()


```
